source 'https://rubygems.org'

gem 'rails', '4.1.6'
gem "letter_opener", :group => :development
gem 'pry-rails'
gem 'faker'

gem 'sqlite3'
group :assets do
  gem 'sass-rails',   '~> 4.0.0.beta1'
  gem 'coffee-rails', '~> 4.0.0.beta1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem 'haml'
gem 'bcrypt-ruby', '3.1.2'
