# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

TodoList::Application.load_tasks

task :setup => :environment do
  require 'faker'
  require 'securerandom'

  [Task, User].each { |c| c.delete_all }

  def generate_password
    SecureRandom.base64(32)
  end

  def a_random_number_under(n)
    SecureRandom.random_number(100)
  end

  def generate_some_dummy_users
    a_random_number_under(20).times do
      print '.'
      user = User.create(
        email: Faker::Internet.email,
        password: (password = generate_password),
        password_confirmation: password,
        dummy: true
      )

      a_random_number_under(5).times do
        user.tasks.create(
          description: Faker::Lorem.sentence
        )
      end
    end
  end

  manhatten = User.create(
    email: 'j.osterman@watchmen.net',
    password: (password = generate_password),
    password_confirmation: password,
    dummy: true
  )

  manhatten.tasks.create(description: 'Rift in the spacetime continuum')
  manhatten.tasks.create(description: 'Be in two places at once')
  manhatten.tasks.create(description: 'Go back in time and create a paradox')
  manhatten.tasks.create(description: 'Grocery shopping')


  generate_some_dummy_users

  
  print "\n"
end
