source 'https://rubygems.org'
gem 'rails', '4.1.6'
gem 'sqlite3'
group :assets do
  gem 'sass-rails',   '~> 4.0.0'
  gem 'coffee-rails', '~> 4.0.0'
  gem 'uglifier', '>= 1.3.0'
end
gem 'jquery-rails'
gem 'bootstrap-sass', '2.3.2.1'
gem 'devise'
gem 'haml-rails'
gem 'thin'
gem 'faker'
gem 'cancan'
group :development do
  gem 'html2haml'
end
group :development, :test do
  gem 'rspec-rails'
end
group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'email_spec'
end
