#!/usr/bin/env rake
# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

PayrollBuddy::Application.load_tasks
require 'faker'
require 'securerandom'

def random_number(opts = {})
  from, to = opts.values_at(:from, :to)
  from + SecureRandom.random_number(to - from)
end

SALARIES = [12, 20, 30, 40, 50, 60, 70, 80, 90, 100].map { |x| 1000 * x }

def create_random_users_in(org)
  random_number(from: 5, to: 20).times do
    user = org.users.build(
      email: Faker::Internet.email,
      name:  Faker::Name.name,
      password: (password = SecureRandom.hex),
      password_confirmation:  password,
      manager: false,
    )
    user.salary = SALARIES.sample
    user.save
    print 'u'
    
    months_ago = random_number(from:3, to: 7)
    1.upto(months_ago) do |i|
      user.payments.create(amount: user.salary, transacted_at: i.months.ago)
      print 'p'
    end
  end

  org.users.last.update_attributes(manager: true)
end

def create_a_bunch_of_random_organisatons
  ActiveRecord::Base.transaction do
    random_number(from: 20, to: 40).times do
      org = Organisation.create(name: Faker::Company.name)
      print 'o'
      create_random_users_in org
    end
  end
end

alias :create_a_bunch_more_organisations :create_a_bunch_of_random_organisatons

task :setup => [:environment, :clear] do
  create_a_bunch_of_random_organisatons

  daily_planet = Organisation.create(name: 'The Daily Planet')
  create_random_users_in daily_planet

  clark = daily_planet.users.build(
    email: 'clark.kent@gmail.com',
    name: 'Clark Kent',
    password: (password = SecureRandom.hex),
    password_confirmation: password,
    manager: false
  )
  clark.salary = 100000
  clark.save

  create_random_users_in daily_planet
    
  create_a_bunch_more_organisations
end

task :clear => :environment do
  [Organisation, User, Payment].each { |k| k.delete_all }
end
