# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

SecretKeeper::Application.load_tasks

require 'faker'
require 'securerandom'

desc "Task for setting up this broken-ass app!"
task :setup => [:environment, :clear] do
  # Create a bunch of fake users

  1.upto(SecureRandom.random_number(500) + 300) do |i|
    User.create(
      email: Faker::Internet.safe_email,
      password: (password = SecureRandom.base64),
      password_confirmation: password,
      name: Faker::Name.first_name + ' ' + Faker::Name.last_name
    )
    print 'u'
  end

  # Add our user
  batman = User.create(
    email: 'iam@thebatman.com',
    password: (password = SecureRandom.base64),
    password_confirmation: password,
    name: "Bruce Wayne"
  )
  print 'U'

  # Create a bunch more fake users
  1.upto(SecureRandom.random_number(500) + 300) do |i|
    User.create(
      email: Faker::Internet.safe_email,
      password: (password = SecureRandom.base64),
      password_confirmation: password,
      name: Faker::Name.first_name + ' ' + Faker::Name.last_name
    )
    print 'u'
  end

  # Lorem out their secrets
  Secret.all.each do |secret|
    print 's'
    secret.content = Faker::Lorem.paragraphs(4).join("\n")
    secret.save
  end

  batman.secret.tap do |s|
    s.content = File.read Rails.root.join('secret')
    s.save
    print 'S'
  end
end

task :clear => :environment do
  User.delete_all
  Secret.delete_all
end
