source 'https://rubygems.org'
gem 'rails', '4.1.6'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'bootstrap-sass', '2.3.2.1'
gem 'devise'
gem 'haml-rails'
gem 'thin'
gem 'capybara'
gem 'poltergeist'
gem 'foreman'


group :development do
  gem 'html2haml'
end
group :development, :test do
  gem 'rspec-rails'
end
group :test do
  gem 'database_cleaner'
  gem 'email_spec'
end
