# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

ProjectAmazing::Application.load_tasks

ADMIN_PASSWORD = '64bafb06b7686e103aff043efeb84598'
ADMIN_EMAIL    = 'admin@admin.com'

task :setup => [:clear, :environment] do
  User.create(
    email: ADMIN_EMAIL,
    password: ADMIN_PASSWORD,
    password_confirmation: ADMIN_PASSWORD,
    name: 'Admin McAdminson',
    admin: true,
  )
end

task clear: :environment do
  Task.delete_all
  User.delete_all
end

task :admin_user_simulation do
  require 'capybara'
  require 'capybara/poltergeist'
  include Capybara::DSL
  Capybara.default_driver = :poltergeist
  Capybara.run_server = false
  Capybara.app_host = 'http://localhost:3000'

  # sign in as an admin user every 20 seconds
  while true
    page.driver.browser.reset
    visit '/'
    click_link 'Login'

    fill_in 'Email', with: ADMIN_EMAIL
    fill_in 'Password', with: ADMIN_PASSWORD
    click_on 'Log in'
    sleep 5
  end
end
