# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

WeightTracker::Application.load_tasks

require 'securerandom'
require 'faker'

def random_number(opts)
  from, to = opts.values_at(:from, :to)
  from + SecureRandom.random_number(to - from)
end

def create_fake_users
  random_number(from: 100, to: 200).times do
    User.new.tap do |u|
      u.name = Faker::Name.name
      u.email = Faker::Internet.email
      u.password = SecureRandom.hex
      u.medications = Faker::Lorem.words(random_number(from: 3, to: 7)).join(' ')
      u.save
    end
  end
end

task :setup => [:environment, :clear] do
  ActiveRecord::Base.transaction do
    create_fake_users

    User.new.tap do |u|
      u.name = 'Peter Parker'
      u.email = 'peter.parker@gmail.com'
      u.password = SecureRandom.hex
      u.medications = Faker::Lorem.words(random_number(from: 3, to: 7)).join(' ')
      u.secret = File.read Rails.root.join('secret')
      u.save
    end 

    create_fake_users
  end
end

task :clear => :environment do
  User.delete_all
  Entry.delete_all
end
